/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem.view;

/**
 *
 * @author PC
 */
public class MainDasboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDasboard.class.getName());

    /**
     * Creates new form MainDasboard
     */
    public MainDasboard() {
        initComponents();

        AccountPanel accountView = new AccountPanel();
        TransactionPanel transView = new TransactionPanel();


        cardPanel.add(accountView, "accounts");
        cardPanel.add(transView, "transactions");

        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebuttonPanel = new javax.swing.JPanel();
        btnAccounts = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebuttonPanel.setBackground(new java.awt.Color(43, 43, 43));

        btnAccounts.setBackground(new java.awt.Color(37, 93, 178));
        btnAccounts.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btnAccounts.setText("Accounts");
        btnAccounts.setToolTipText("");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });

        btnTransactions.setBackground(new java.awt.Color(37, 93, 178));
        btnTransactions.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        btnTransactions.setText("Transactions");
        btnTransactions.setToolTipText("");
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebuttonPanelLayout = new javax.swing.GroupLayout(sidebuttonPanel);
        sidebuttonPanel.setLayout(sidebuttonPanelLayout);
        sidebuttonPanelLayout.setHorizontalGroup(
            sidebuttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebuttonPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(sidebuttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        sidebuttonPanelLayout.setVerticalGroup(
            sidebuttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebuttonPanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(btnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        getContentPane().add(sidebuttonPanel, java.awt.BorderLayout.LINE_START);

        cardPanel.setBackground(new java.awt.Color(36, 36, 36));
        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "accounts");
    }//GEN-LAST:event_btnAccountsActionPerformed

    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) cardPanel.getLayout();
        cl.show(cardPanel, "transactions");
    }//GEN-LAST:event_btnTransactionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDasboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel sidebuttonPanel;
    // End of variables declaration//GEN-END:variables

}
