/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bankingsystem.view;

import bankingsystem.dao.DBConnection;

/**
 *
 * @author PC
 */
public class TransactionPanel extends javax.swing.JPanel {

  
    public TransactionPanel() {
        initComponents();

        javax.swing.JSpinner.DefaultEditor editor = (javax.swing.JSpinner.DefaultEditor) spnAmount.getEditor();
        javax.swing.JFormattedTextField textField = editor.getTextField();

        textField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        textField.selectAll();
                    }
                });
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accdetails_Text = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccountId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        spnAmount = new javax.swing.JSpinner();
        btnView = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(36, 36, 36));

        accdetails_Text.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        accdetails_Text.setForeground(new java.awt.Color(255, 255, 255));
        accdetails_Text.setText("Deposit/Withdraw");
        accdetails_Text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account ID");

        txtAccountId.setPreferredSize(new java.awt.Dimension(400, 35));
        txtAccountId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");

        btnDeposit.setBackground(new java.awt.Color(200, 103, 39));
        btnDeposit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDeposit.setForeground(new java.awt.Color(255, 255, 255));
        btnDeposit.setText("Deposit");
        btnDeposit.setBorderPainted(false);
        btnDeposit.setFocusPainted(false);
        btnDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepositMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepositMouseExited(evt);
            }
        });
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setBackground(new java.awt.Color(200, 103, 39));
        btnWithdraw.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        btnWithdraw.setText("Withdraw");
        btnWithdraw.setBorderPainted(false);
        btnWithdraw.setFocusPainted(false);
        btnWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWithdrawMouseExited(evt);
            }
        });
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(51, 51, 51));
        btnView.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("See Accounts");
        btnView.setBorderPainted(false);
        btnView.setFocusPainted(false);
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
        });
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(accdetails_Text))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAccountId, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnAmount))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(accdetails_Text)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAccountId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(spnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountIdActionPerformed

    private void btnDepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseEntered
        btnDeposit.setBackground(new java.awt.Color(222, 132, 73));
    }//GEN-LAST:event_btnDepositMouseEntered

    private void btnDepositMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositMouseExited
        btnDeposit.setBackground(new java.awt.Color(200, 103, 39));
    }//GEN-LAST:event_btnDepositMouseExited

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed

        if (txtAccountId.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID.");
            return;
        }

        try {
            int accountId = Integer.parseInt(txtAccountId.getText().trim());
            double depositAmount = Double.parseDouble(spnAmount.getValue().toString());

            if (depositAmount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid amount greater than $0.");
                return;
            }

            bankingsystem.dao.AccountDAO dao = new bankingsystem.dao.AccountDAO();

            double currentBalance = dao.getAccountBalance(accountId);
            if (currentBalance == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Account not found! Please check the Account ID.");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to deposit $" + depositAmount + " to Account #" + accountId + "?\nNew Balance will be: $" + (currentBalance + depositAmount),
                    "Confirm Deposit",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {

                dao.depositToAccount(accountId, depositAmount);

                String receiptDetails = "=== TRANSACTION SUCCESSFUL ===\n\n"
                        + "Account ID: " + accountId + "\n"
                        + "Transaction Type: DEPOSIT\n"
                        + "Amount: $" + depositAmount + "\n"
                        + "\n==============================";

                Object[] options = {"Close", "See Transactions"};

                int choice = javax.swing.JOptionPane.showOptionDialog(this,
                        receiptDetails,
                        "Transaction Receipt",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options,
                        options[0]);

                if (choice == 1) {
                    bankingsystem.view.HistoryFrame historyWindow = new bankingsystem.view.HistoryFrame();
                    historyWindow.setVisible(true);
                }
                // ---------------------------------

                txtAccountId.setText("");
                spnAmount.setValue(0);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Account ID number.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWithdrawMouseEntered

    private void btnWithdrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithdrawMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWithdrawMouseExited

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed

        if (txtAccountId.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an Account ID.");
            return;
        }

        try {
            int accountId = Integer.parseInt(txtAccountId.getText().trim());
            double withdrawAmount = Double.parseDouble(spnAmount.getValue().toString());

            if (withdrawAmount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid amount greater than $0.");
                return;
            }

            bankingsystem.dao.AccountDAO dao = new bankingsystem.dao.AccountDAO();

            double currentBalance = dao.getAccountBalance(accountId);
            if (currentBalance == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Account not found! Please check the Account ID.");
                return;
            }

            if (currentBalance < withdrawAmount) {
                javax.swing.JOptionPane.showMessageDialog(this, "Insufficient funds!\nCurrent balance is only: $" + currentBalance);
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to withdraw $" + withdrawAmount + " from Account #" + accountId + "?\nNew Balance will be: $" + (currentBalance - withdrawAmount),
                    "Confirm Withdrawal",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                // Process the withdrawal in the database
                dao.withdrawFromAccount(accountId, withdrawAmount);

                // --- RECEIPT POP-UP LOGIC ---
                String receiptDetails = "=== TRANSACTION SUCCESSFUL ===\n\n"
                        + "Account ID: " + accountId + "\n"
                        + "Transaction Type: WITHDRAW\n"
                        + "Amount: $" + withdrawAmount + "\n"
                        + "\n==============================";

                Object[] options = {"Close", "See Transactions"};

                int choice = javax.swing.JOptionPane.showOptionDialog(this,
                        receiptDetails,
                        "Transaction Receipt",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options,
                        options[0]);

                if (choice == 1) {

                    bankingsystem.view.HistoryFrame historyWindow = new bankingsystem.view.HistoryFrame();
                    historyWindow.setVisible(true);
                }
                // ---------------------------------

                txtAccountId.setText("");
                spnAmount.setValue(0);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Account ID number.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMouseEntered

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewMouseExited

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        AccountListFrame listFrame = new AccountListFrame();
        listFrame.setVisible(true);
        listFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accdetails_Text;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnAmount;
    private javax.swing.JTextField txtAccountId;
    // End of variables declaration//GEN-END:variables
}
